### PR TITLE
Fixed English and grammar mistakes

### PR DESCRIPTION
**Pull request by thezakman**
Few lines fixed.

### CODE REVIEW

**Comment by wf9a5m75** [comment]
Thank you.

**Comment by wf9a5m75** [comment]
Are you interested in to this project?

**Comment by thezakman** [comment]
No problem, I'm glad to help!
And Yes I am interested.

**Comment by wf9a5m75** [comment]
Please tell me your e-mail address. I will invite you to the slack channel.
(If you don't want to discover your e-mail at here, please contact to my e-mail address)

**Comment by thezakman** [comment]
Sent you an e-mail just now!

**Comment by wf9a5m75** [comment]
Thank you. I'm writing an e-mail for you. 
And I already sent the invitation to the slack channel.
Please join the slack channel in advance.

**Pull request merged**
